config/routes.rb
Rails.application.routes.draw do

  resources :qualifications
  resources :skills
  resources :notifications, only: [:show, :index]

  resources :job_requests do
      resource :transitions, as: :transition, only: :update, controller: "job_requests/transitions"
      resources :job_applications, only: [:show, :index, :update]
      resources :comments, only: :create
  end

  resources :profiles, only: [:update, :show] do
    resource :switch_profile, as: :switch, only: :update, controller: 'profiles/switch_profiles'
  end

  devise_for :users, except: :show, :controllers => { registrations: 'registrations' }

  resources :users, only: [] do
    resources :comments, only: :create
  end



  #resource :posts

  get '/users' => 'users#index'
  get '/users/:id' => 'users#show', as: 'user'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'

end

app/models/job_request.rb
class JobRequest < ActiveRecord::Base

  # Allow searching via states
  include Statesman::Adapters::ActiveRecordQueries
  def self.transition_name
    :transitions
  end

  def self.transition_class
    JobRequestTransition
  end
  private_class_method :transition_class

  def self.initial_state
    JobRequestStateMachine.initial_state
  end
  private_class_method :initial_state

  belongs_to :profile
  has_many :transitions, class_name: "JobRequestTransition", autosave: false
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :job_applications, dependent: :destroy

  scope :order_by_date, -> { order(created_at: :desc) }
  scope :open, -> { in_state(:open) }

  scope :not_owner, -> (profile) { where('profile_id != ?', profile.id) }
  scope :owned_by_current_user, -> (profile) { where('profile_id = ?', profile.id) }
  scope :application_accepted, -> { in_state(:application_accepted) }

  delegate :current_state, :in_state?, to: :state_machine

  def state_machine
    @state_machine ||= JobRequestStateMachine.new(self, transition_class: JobRequestTransition,
                                                   association_name: :transitions)
  end
end

app/controllers/job_requests/register_applications_controller.rb
class JobRequests::RegisterApplicationsController <  ApplicationController
  def update
    flash[:success] = "Where is this???"

    redirect_to :back
  end
end

app/controllers/job_requests/transitions_controller.rb
class JobRequests::TransitionsController < ApplicationController

  def update
    @job_request = JobRequest.find(params[:job_request_id])

    if @job_request.state_machine.current_state == "open"
      was_created = false
      application = @job_request.job_applications.find_or_create_by(user_id: current_user.id) do |application|
        if application.new_record?
          # create claimed job, mirroring job request
          current_user.profiles.find_by(profile_type: 0).claimed_jobs.create(job_request_id: @job_request.id)
          was_created = true
          flash[:success] = "Application lodged! Good luck!"
        end
      end

      if was_created == false
        flash[:info] = "Application already submitted. Good luck."
      end
      redirect_to :back

    elsif @job_request.state_machine.current_state == "application_accepted"
      # job is now complete!
      @job_request.state_machine.transition_to!(:completed)
      flash[:success] = "Job completed!"
      redirect_to :back
    end
  end
end

app/controllers/job_requests_controller.rb
class JobRequestsController < ApplicationController
  before_action :set_job_request, only: [:show, :edit, :destroy, :update]

  def create
    @job_request = current_recruiter.job_requests.new(job_request_params)
    authorize(@job_request)

    if @job_request.save
      redirect_to session[:referer], notice: "Saved new job request."
    else
      redirect_to session[:referer], alert: "Error. Please check all the fields are correct and try again."
    end
  end

  def edit
    save_referer
  end

  def update
    if @job_request.update(job_request_params)
      redirect_to session[:referer], notice: "Updated job request."
    else
      redirect_to session[:referer], notice: "Unable to update job request. Check fields are correct and try again."
    end
  end

  def destroy
    @job_request.destroy
    flash[:success] = 'Job request was successfully deleted.'
    redirect_to :back
  end

  def index
    authorize(JobRequest)
    @job_requests = JobRequest.all.not_owner(current_recruiter).order_by_date.open
  end

  def show
    @current_profile_type = current_user_profile
    @comment = @job_request.comments.new
    @comments = @job_request.comments.all

    @recruiter_profile = Profile.find(@job_request.profile_id)
    @recruiter = User.find(@recruiter_profile.user_id)

    @message = @recruiter.comments.new
  end

  def new
    @job_request = current_recruiter.job_requests.new
    authorize(@job_request)
    save_referer
  end

  private

  def save_referer
    session[:referer] = request.referer
  end

  def set_job_request
    @job_request = JobRequest.find(params[:id])
    authorize(@job_request)
  end

  def job_request_params
    params.require(:job_request).permit(:name, :details)
  end
end

app/helpers/job_requests_helper.rb
module JobRequestsHelper
end

app/views/job_requests/_job_request.html.erb
<div class="ui two column grid">
  <div class="seven wide column">
    <div class="ui segment">
      <div class="ui items">
        <div class="content">
        <%= request.name %>
        <%= format_time(request.created_at) %>
          <div class="details">
            <%= request.details %>
          </div>
          <div class="extra">
            <br />TODO: Tags. State: <%= request.state_machine.current_state %>
          </div>
          
        </div>
      </div>
    </div>
  </div>

  <div class="one wide column">
    <h3>
    <% if policy(request).edit? %>
      <%= link_to edit_job_request_path(request), class: 'left-floated', title: "Edit" do %>
        <i class="edit icon"></i>
      <% end %>
    <% end %>

    <% if policy(request).show? %>
      <%= link_to job_request_path(request), class: 'left-floated', title: "Show" do %>
        <i class="unhide icon"></i>
      <% end %>
    <% end %>

    <% if policy(request).destroy? %>
      <%= link_to job_request_path(request), method: :delete, data: { confirm: "Are you sure?" }, class: 'left-floated' do %>
        <i class="red remove icon"></i>
      <% end %>
    <% end %>

    <% if policy(request).destroy? %>
      <%= link_to job_request_job_applications_path(request), class: 'left-floated', title: "Applications" do %>
        <i class="mail outline icon"></i>
      <% end %>
    <% end %>
    </h3>
  </div>
</div>

app/views/job_requests/create.html.erb
<h1>JobRequests#create</h1>
<p>Find me in app/views/job_requests/create.html.erb</p>

app/views/job_requests/destroy.html.erb
<h1>JobRequests#destroy</h1>
<p>Find me in app/views/job_requests/destroy.html.erb</p>

app/views/job_requests/edit.html.erb
<div class="ui three column grid">
  <div class="two wide column">
    <!-- filler -->
  </div>

  <div class="six wide column">
    <h1>Edit Job Request</h1>

    <%= semantic_form_for(@job_request, html: { class: 'ui form', method: :put }) do |f| %>
      <%= f.input :name, label: false, wrapper_html: { class: 'field' }, :input_html => { rows: 1 } %>
      <%= f.input :details, label: false, wrapper_html: { class: 'field' }, :input_html => { rows: 4 } %>
      <%= f.action :submit, label: 'Update Job Request', button_html: { class: 'small right floated ui blue submit button' } %>
    <% end %>
  </div>
</div>

app/views/job_requests/index.html.erb
<div class="ui three column grid">
  <div class="two wide column">
    <!--  LHS column -->
  </div>

  <div class="twelve wide column">
    <h2>Browse Job Opportunities</h2>

    <% @job_requests.each do |request| %>
      <%= render 'job_requests/job_request', { request: request } %>
    <% end %>
  </div>

  <div class="two wide column">
    <!--  LHS column -->
  </div>
</div>

app/views/job_requests/new.html.erb
<div class="ui three column grid">
  <div class="two wide column">

  </div>
  <div class="twelve wide column">
    <h1>JobRequests#new</h1>
    <p>Find me in app/views/job_requests/new.html.erb</p>

    <%= semantic_form_for(@job_request, html: { class: 'ui form'}) do |f| %>
      <%= f.input :name, label: false, placeholder: "Job Title", wrapper_html: { class: 'field' } %>
      <%= f.input :details, label: false, placeholder: "Job details", wrapper_html: { class: 'field' }, input_html: { rows: 8 } %>
      <%= f.action :submit, label: 'Submit Job', button_html: { class: 'small right floated ui blue submit button' } %>
    <% end %>
  </div>
  <div class="two wide column">

  </div>
</div>

app/views/job_requests/show.html.erb
<div class="ui four column stackable grid">
  <div class="two wide column">
    <!--  LHS column -->
  </div>
  <div class="six wide column">
    <div class="ui fluid card">
      <div class="content">
        <div class="title"><b><%= @job_request.name %></b>
          <span class="right floated time">
            <%= format_time(@job_request.created_at) %>
          </span>
        </div><br>
        <div class="details">
          <%= @job_request.details %>
        </div><br>
        <div class="further_information">
          <%= @job_request.further_information %>
        </div>
      </div>
      <% if @current_user_profile == '0' %>
        <%= link_to main_app.job_request_transition_path(@job_request), data: { }, method: :patch, class: 'ui bottom attached button' do %>
          Apply
        <% end %>
      <% end %>
    </div>

    <div class="ui fluid card">
      <div class="image">

      </div>
      <div class="content">
        <div class="header"><%= @recruiter.name %></div>
        <div class="meta">Posted at <%= format_time(@job_request.created_at) %></div>
      </div>
      <div class="extra content">
        X Job completed
        <span class="right floated"><%= button_tag "Message #{@recruiter.name}", type: 'button', id: 'show-message-form', class: 'ui right floated small button' %></span>
      </div>
    </div>

    <div class="" id="message-form">
      <%= render partial: 'comments/form', locals: { comment: [@recruiter, @message], placeholder: "Write a message...", submit_button_text: "Send Message" } %>
    </div>
  </div>

  <div class="six wide column" id="job-request-comment-form">
    <% if policy(@job_request).update? %>
      <%= link_to main_app.job_request_transition_path(@job_request),  method: :patch, title: "Complete", class: 'ui positive right floated button' do %>
        Mark as complete
      <% end %>
      <br />
    <% end %>

    <%= render 'comments/comment', { comments: @comments } %>
    <%= render partial: 'comments/form', locals: { comment: [@job_request, @comment], submit_button_text: "Post Comment" } %>
  </div>

  <div class="two wide column">
    <!-- RHS column -->
  </div>
</div>


<script>
  $(function () {
    JobRequests.messageFormInit();
  });
</script>

app/views/job_requests/update.html.erb
<h1>JobRequests#update</h1>
<p>Find me in app/views/job_requests/update.html.erb</p>