config/routes.rb
Rails.application.routes.draw do

  resources :qualifications
  resources :skills
  resources :notifications, only: [:show, :index]

  resources :job_requests do
      resource :transitions, as: :transition, only: :update, controller: "job_requests/transitions"
      resources :job_applications, only: [:show, :index, :update]
      resources :comments, only: :create
  end

  resources :profiles, only: [:update, :show] do
    resource :switch_profile, as: :switch, only: :update, controller: 'profiles/switch_profiles'
  end

  devise_for :users, except: :show, :controllers => { registrations: 'registrations' }

  resources :users, only: [] do
    resources :comments, only: :create
  end



  #resource :posts

  get '/users' => 'users#index'
  get '/users/:id' => 'users#show', as: 'user'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  scope :unseen_notifications, -> { where(seen: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  include ApplicationHelper

  def show
    @notification = Notification.find(params[:id])
    @notification.update_attributes(seen: true)
    @comment = Comment.find(@notification.comment_id)
  end

  def index
    authorize(Notification)
    @notifications = current_user.notifications.all.unseen_notifications
    @job_application_notifications = job_application_notifications
    @job_requests = []
    @job_application_notifications.each do |n|
      @job_requests.push(JobRequest.find(n.job_request_id))
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<div class="ui four column stackable grid">
  <div class="two wide column">
    <!--  LHS column -->
  </div>

  <div class="six wide column">
    <h1>Message and Comments</h1>
    <% @notifications.each do |n| %>
      <%= link_to "Notification #{n.id}", n %>
    <% end %>

    <h1>Job Applications</h1>
    <% @job_application_notifications.each_with_index do |application, idx| %>

    <div class="ui fluid card">
      <div class="content">
        <div class="title">
          Application received for: <%= link_to "#{@job_requests[idx].name}", job_request_path(@job_requests[idx]) %><br />
          <span class="right floated">
            <%#= link_to "View #{@applicants[idx].name}'s Profile", profile_path(@applicants[idx].profiles.first) %>
          </span>
        </div>
        <div class="application_message">
          Message: <%= application.application_message %>
        </div>
      </div>
    </div>
  <% end %>
  </div>

  <div class="six wide column">

  </div>

  <div class="two wide column">
    <!--  RHS column -->
  </div>

app/views/notifications/show.html.erb
<h1>Notifications#show</h1>
<p>Find me in app/views/notifications/show.html.erb</p>
<%= @comment.message %>
<%= @notification.seen %>