config/routes.rb
Rails.application.routes.draw do

  resources :qualifications
  resources :skills
  resources :notifications, only: [:show, :index]

  resources :job_requests do
      resource :transitions, as: :transition, only: :update, controller: "job_requests/transitions"
      resources :job_applications, only: [:show, :index, :update]
      resources :comments, only: :create
  end

  resources :profiles, only: [:update, :show] do
    resource :switch_profile, as: :switch, only: :update, controller: 'profiles/switch_profiles'
  end

  devise_for :users, except: :show, :controllers => { registrations: 'registrations' }

  resources :users, only: [] do
    resources :comments, only: :create
  end



  #resource :posts

  get '/users' => 'users#index'
  get '/users/:id' => 'users#show', as: 'user'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'

end

app/models/claimed_job.rb
class ClaimedJob < ActiveRecord::Base
  belongs_to :profile

  scope :requests, -> (claimed_jobs) { JobRequest.where(id: claimed_jobs.pluck(:job_request_id)) }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  belongs_to :notification
end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base
  belongs_to :job_request

  scope :filter_by_job, -> (job_request) { where("job_request_id = ?", job_request.id) }
  scope :filter_by_jobs, -> (job_requests) { where(job_request_id: job_requests.collect(&:id)) }
  scope :filter_by_unseen, -> { where(seen: false) }
end

app/models/job_request.rb
class JobRequest < ActiveRecord::Base

  # Allow searching via states
  include Statesman::Adapters::ActiveRecordQueries
  def self.transition_name
    :transitions
  end

  def self.transition_class
    JobRequestTransition
  end
  private_class_method :transition_class

  def self.initial_state
    JobRequestStateMachine.initial_state
  end
  private_class_method :initial_state

  belongs_to :profile
  has_many :transitions, class_name: "JobRequestTransition", autosave: false
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :job_applications, dependent: :destroy

  scope :order_by_date, -> { order(created_at: :desc) }
  scope :open, -> { in_state(:open) }

  scope :not_owner, -> (profile) { where('profile_id != ?', profile.id) }
  scope :owned_by_current_user, -> (profile) { where('profile_id = ?', profile.id) }
  scope :application_accepted, -> { in_state(:application_accepted) }

  delegate :current_state, :in_state?, to: :state_machine

  def state_machine
    @state_machine ||= JobRequestStateMachine.new(self, transition_class: JobRequestTransition,
                                                   association_name: :transitions)
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  scope :unseen_notifications, -> { where(seen: false) }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  enum profile_type: [:employee, :employer]
  after_initialize :set_default_role, :if => :new_record?

  belongs_to :user
  has_many :qualifications
  has_many :skills
  has_many :job_requests
  has_many :claimed_jobs
  has_many :comments, as: :commentable

  def set_default_role
    self.profile_type ||= :employee
  end
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
  belongs_to :profile
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :profile
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :editor, :admin]
  after_initialize :set_default_role, if: :new_record?
  after_create :set_up_profiles


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many(:profiles)
  has_many :notifications
  has_many :comments, as: :commentable
  private

  def set_default_role
    self.role ||= :user
  end

  def set_up_profiles
    self.profiles.create!(self_introduction: "Update your self introduction!", profile_type: 0)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_user_profile
  def index
    @skills = @profile.skills.all

    @skill = @profile.skills.build # new skill form
  end

  def update
    @skill = Skill.find_by(id: params[:id])

    if @skill.update(skills_params)
      redirect_to skills_path, notice: "Updated skill."
    else
      redirect_to skills_path, notice: "Unable to update skill. Check fields are correct and try again."
    end
  end

  def edit
    @skill = Skill.find_by(id: params[:id])
  end

  def create
    @skill = @profile.skills.new(skills_params)

    if @skill.save
      redirect_to skills_path, notice: "Saved new skill."
    else
      redirect_to :back, alert: "Error. Please check all the fields are correct and try again."
    end
  end

  def destroy
    puts "Params", params
    puts "params id " , params[:id]
    @skill = Skill.find_by(id: params[:id])
    puts @skill.inspect

    @skill.destroy
    flash[:success] = 'skill was successfully deleted.'
    redirect_to action: 'index'
  end

  private

  def set_user_profile
    @profile = current_user.profiles.find_by(profile_type: 0)
  end

  def skills_params
    params.require(:skill).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
    authorize(User) # activate policy
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to root_path
      # save
    else
      render 'edit', alert: "Error"
    end
  end

  def show
    if user_signed_in?
      @user = User.find(params[:id])

      if current_user_profile.eql? '0'
        @profile = @user.profiles.find_by(profile_type: 0)
        @qualifications = @profile.qualifications.all
        @skills = @profile.skills.all
        @active_jobs = @profile.claimed_jobs.requests(@profile.claimed_jobs)
        @accepted_applications = @active_jobs.application_accepted
        @active_jobs = @active_jobs - @accepted_applications
      else
        @profile = @user.profiles.find_by(profile_type: 1)
        @job_requests = @profile.job_requests.all.order_by_date
        @open_jobs = @job_requests.open
        @accepted_applications = @job_requests.application_accepted
      end
    else
      # display a flash
      flash[:danger] = "Please log in to view user profiles."
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when 'success' then "ui positive message"
      when 'error'   then "ui red message"
      when 'info'    then "ui info message"
      when 'warning' then 'ui negative message'
    end
  end

  def format_time(time)
    time.strftime('%x %H:%M')
  end

  def notifications
    current_user.notifications.unseen_notifications.count + job_application_notifications.count
  end

  def job_application_notifications
    user_job_requests = JobRequest.owned_by_current_user(current_user.profiles.find_by(profile_type: 1))
    user_job_request_applications = JobApplication.filter_by_jobs(user_job_requests)
    unseen_applications = user_job_request_applications.filter_by_unseen
  end

  def current_recruiter
    current_user.profiles.find_by(profile_type: 1)
  end

  def current_freelancer
    current_user.profiles.find_by(profile_type: 0)
  end

  def under_recruiter?
    session[:current_profile_id].eql? '1'
  end

  def under_freelancer?
    session[:current_profile_id].eql? '0'
  end

  def full_title(page_title = '')
    base_title = "MyService"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/claimed_jobs_helper.rb
module ClaimedJobsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/job_requests_helper.rb
module JobRequestsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/users/_bio.html.erb
<table class="ui celled definition table">
  <tbody>
    <tr>
      <td class="collapsing">My skills are:</td>
      <td>
        <%= @skills.map do |skill| skill.description end.join(', ').html_safe %>
      </td>
    </tr>
    <tr>
      <td class="collapsing">My qualifications include:</td>
      <td>

      <% @qualifications.each_with_index do |qualification| %>
          <%= "<br />".html_safe unless qualification == @qualifications.first %>
          <div class="">
            <%= qualification.name %>
          </div>
           - <%= qualification.description %><br />

      <% end %>
    </td>
    </tr>
    <tr>
      <td class="collapsing">Self introduction:</td>
      <td><%= @profile.self_introduction %></td>
    </tr>
  </tbody>
</table>

app/views/users/_profile_overview.html.erb
<table class="ui table">
  <thead>
    <tr>
      <th colspan="3">
      <%= @user.name %>
      <% if current_user == @user %>
        <%= link_to qualifications_path, class: "ui right floated small labeled icon button", title: "Edit" do %>
          <i class="edit icon"></i> Edit Qualifications
        <% end %>
        <%= link_to skills_path, class: "ui right floated small labeled icon button", title: "Edit" do %>
          <i class="edit icon"></i> Edit Skills
        <% end %>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <tr class="top aligned">
      <td class="collapsing">
        <%= image_tag("profile_picture.jpg", height: 200) %>
      </td>
      <td>
        <%= render partial: "bio" %>
      </td>
    </tr>

  </tbody>
</table>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Update" %>
    </div>
<% end %>

<h3>Cancel my account</h3>


<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
  <li>
    <%= link_to(user.name, user_path(user.id)) %>
    <% if current_user.admin? %>
      <%= link_to("Edit", edit_user_registration_path(user)) %>
    <% end %>
  </li>
<% end %>

app/views/users/show.html.erb
<div class="ui three column grid">
  <div class="two wide column">
    <!--  LHS column -->
  </div>

  <% if session[:current_profile_id].eql? '0' %> <!-- freelancer profile -->
    <div class="twelve wide column">
      <h1>Profile</h1>

      <h2>Job you've applied for</h2>
        <% @active_jobs.each do |job| %>
          <%#= render 'claimed_jobs/claimed_job', { request: job } %>
          <%= render 'job_requests/job_request', { request: job } %>
        <% end %>

      <h2>Jobs you are current working on</h2>
      <% @accepted_applications.each do |application| %>
        <%= render 'job_requests/job_request', { request: application } %>
      <% end %>

      <h2>Your public profile</h2>

      <%= render partial: "profile_overview" %>

      <%= semantic_form_for(@profile, html: { class: 'ui form', method: :put}) do |f| %>
        <%= f.input :self_introduction, label: 'Update self introduction', wrapper_html: { class: 'field' }, input_html: { rows: '5'} %>

        <%= f.action :submit, button_html: { class: 'ui small right floated blue submit button' } %>
      <% end %>
    </div>

  <% elsif session[:current_profile_id].eql? '1' %> <!-- Recruiter -->

    <div class="twelve wide column">
      <h2>Profile</h2>

      <%= link_to new_job_request_path, class: 'ui right floated small labeled icon blue button' do %>
        <i class="add circle icon"></i>New Job Request
      <% end %>
      
      <h2>Jobs you are currently advertising</h2>
        <% @open_jobs.each do |job| %>
          <%= render 'job_requests/job_request', { request: job } %>
        <% end %>

      <h2>Jobs in progress</h2>
        <% @accepted_applications.each do |job| %>
          <%= render 'job_requests/job_request', { request: job } %>
        <% end %>
      </div>

  <% end %>

  <div class="two wide column">
    <!--  RHS column -->
  </div>
</div>